id: PF5448DA9
initial_creation_type: input
source_metadata:
  title: Minling Terchen Gyurme Dorje Series
  language: nl
  description: 'Texts by the famous treasure-revealer Gyurme Dorje (''gyur med rdo
    rje, 1646–1714) alias Terdak Lingpa (gter bdag gling pa), the founder of Mindroling
    Monastery:'
  volume:
    32143437b3d74ad4888abc438067a1ec:
      title: The Secret Vajra Knot
      parent: Aspiration Prayers
    e39cb71bc3184f69a625ffcfa597c3ca:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      parent: Bardo
    1b52a120671b4738ba18849916becc4e:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: Dharma Protectors
    d45d408285cb494bbe82ff9b2a9b0402:
      title: General Long-Life Prayer
      parent: Longevity
    caa338bb77464792b79f7af14dc2ff96:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Sādhanas
    e1f59cc395954efd9b95e7aa12a730a7:
      title: 'Final Words: The Essential Advice'
      parent: Testament
created_at: '2022-03-01T00:48:16.498993'
last_modified_at: '2022-03-01T00:48:16.498999'
